### PR TITLE
Fix gc pikaday - redraw calendar to soonest possible date

### PR DESCRIPTION
**Pull request by samjewell**
Fixes the bug introduced by PR https://github.com/gocardless/dashboard-client/pull/166, and fixes the bug that that PR was attempting to fix

### CODE REVIEW

**Comment by jackfranklin** [comment]
:+1:

**Comment by samjewell** [comment]
@harrison not sure why this is failing tests, just having a look now...

**Comment by jackfranklin** [comment]
@jacobpgn FYI

**Comment by jacobpgn** [comment]
Incredible, thanks guys!

**Comment by harrison** [comment]
:+1:

**Pull request merged**
